# Generated by Django 5.2.9 on 2026-02-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('scifi', 'Sci-Fi'), ('retro', 'Retro')], default='scifi', max_length=10),
        ),
    ]
