# Generated by Django 5.2.9 on 2026-02-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Minimalist Dark'), ('neo-brutalism', 'Neo Brutalism')], default='dark', max_length=20),
        ),
    ]
