# Generated by Django 5.2.9 on 2026-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('dark', 'Cyberpunk Dark'), ('neo-brutalism', 'Neo Brutalism'), ('joyce', 'Joyce')], default='dark', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
