# Generated by Django 5.2.9 on 2026-02-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
