# Generated by Django 5.2.9 on 2026-03-31 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_chatroommember_chatroommessage_and_more'),
        ('notifications', '0002_rename_related_post_notification_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chatroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('upvote', 'Upvote'), ('downvote', 'Downvote'), ('new_post', 'New Post'), ('reply', 'Reply'), ('chatroom_invite', 'Chatroom Invite')], max_length=20),
        ),
    ]
